[project]
name = "wishlists_backend"
version = "0.1.0"
description = "FastAPI backend for Wish Lists web app"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.4",
]
